# Generated by Django 4.2.8 on 2026-04-29 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=100)),
                ('team_member', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('business_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remarks', models.TextField(blank=True)),
                ('import_date', models.DateField(blank=True, help_text='Date/Month of this import', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Detail',
                'verbose_name_plural': 'Attendance Details',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=100)),
                ('team_member', models.CharField(max_length=100)),
                ('business_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('project_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('import_date', models.DateField(blank=True, help_text='Date/Month of this import', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('PUBLIC_HOLIDAY', 'Public Holiday'), ('WEEKEND', 'Weekend'), ('SPECIAL_HOLIDAY', 'Special Holiday')], max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=100)),
                ('team_member', models.CharField(max_length=100)),
                ('project_id', models.IntegerField()),
                ('project', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time_logged', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.TextField(blank=True)),
                ('import_date', models.DateField(blank=True, help_text='Date/Month of this import', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timesheet Detail',
                'verbose_name_plural': 'Timesheet Details',
            },
        ),
        migrations.CreateModel(
            name='TimesheetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=100)),
                ('team_member', models.CharField(max_length=100)),
                ('project_id', models.IntegerField()),
                ('project', models.CharField(max_length=100)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('import_date', models.DateField(blank=True, help_text='Date/Month of this import', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timesheet Summary',
                'verbose_name_plural': 'Timesheet Summaries',
            },
        ),
        migrations.CreateModel(
            name='TimesheetImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField(help_text='Date of the timesheet being imported (e.g., last day of month)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this import')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timesheet Import Log',
                'verbose_name_plural': 'Timesheet Import Logs',
                'ordering': ['-import_date', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('project_code', models.IntegerField()),
                ('manager', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['project_id'],
                'indexes': [models.Index(fields=['department_name'], name='timesheet_p_departm_fb1cbf_idx'), models.Index(fields=['project'], name='timesheet_p_project_f743ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timesheet.project')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_date', models.DateField(blank=True, null=True)),
                ('compoff_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TAKEN', 'Taken')], default='PENDING', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compoffs', to='timesheet.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('project', models.CharField(max_length=100)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='timesheet.employee')),
            ],
            options={
                'verbose_name': 'Timesheet Entry',
                'verbose_name_plural': 'Timesheet Entries',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='timesheet_t_employe_55bbe2_idx'), models.Index(fields=['status'], name='timesheet_t_status_d31984_idx')],
                'unique_together': {('employee', 'date', 'project')},
            },
        ),
    ]
