# Generated by Django 4.2.8 on 2026-06-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_add_us_holiday_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_date', models.DateField(blank=True, help_text='Date when work was done to earn the accrual', null=True)),
                ('adjusted_date', models.DateField(blank=True, help_text='Date when accrual was adjusted/set off', null=True)),
                ('adjustment_reason', models.CharField(blank=True, choices=[('LEAVE_TAKEN', 'Leave Taken on Weekday'), ('PUBLIC_HOLIDAY_OFF', 'Off on Public Holiday')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ADJUSTED', 'Adjusted')], default='PENDING', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='timesheet.employee')),
            ],
            options={
                'verbose_name': 'Accrual',
                'verbose_name_plural': 'Accruals',
                'ordering': ['-created_date'],
            },
        ),
    ]
